#!/usr/bin/env python3
"""Generate `laya.lang`'s word lists and script ranges as Java source.

Compiled in rather than read from `fixtures/lang_tables.json`, because a runtime library must not
depend on a test fixture being on disk. The fixture keeps its job: `LanguageTablesTest` asserts the
compiled copy equals it, so a table that drifts from Python fails a test rather than changing a
routing decision quietly.

TWO ORDERINGS ARE LOAD-BEARING and are preserved deliberately:

  * `_SCRIPT_RANGES` is scanned in order and the FIRST matching range wins, so a reordering
    changes which script a code point is counted under.
  * `_STOP` is iterated to build the per-language scores, and `max` returns the FIRST of equal
    values, so its insertion order decides ties between languages with the same score.

    python laya-java/scripts/gen_language_tables.py            # write
    python laya-java/scripts/gen_language_tables.py --check     # fail if the committed copy differs
"""
import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
TARGET = os.path.join(
    HERE, "..", "laya-java", "src", "main", "java", "com", "convaiinnovations", "laya", "lang",
    "LanguageTables.java")


def quote(text):
    """A Java string literal, with every non-ASCII character escaped so the file stays ASCII."""
    out = ['"']
    for ch in text:
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif " " <= ch <= "~":
            out.append(ch)
        else:
            encoded = ch.encode("utf-16-be")
            for i in range(0, len(encoded), 2):
                out.append("\\u%02X%02X" % (encoded[i], encoded[i + 1]))
    out.append('"')
    return "".join(out)


def words_block(name, words, doc, sort=True):
    items = sorted(words) if sort else list(words)
    lines, current = [], "            "
    for word in items:
        piece = quote(word) + ", "
        if len(current) + len(piece) > 104:
            lines.append(current.rstrip())
            current = "            "
        current += piece
    if current.strip():
        lines.append(current.rstrip().rstrip(","))
    return ('    /** %s */\n    public static final Set<String> %s = Set.of(\n%s);\n'
            % (doc, name, "\n".join(lines)))


def render():
    sys.path.insert(0, REPO)
    from laya import lang

    script_rows = []
    for name, ranges in lang._SCRIPT_RANGES:
        pairs = ", ".join("%d, %d" % (lo, hi) for lo, hi in ranges)
        script_rows.append('            new Script(%s, new int[] {%s})' % (quote(name), pairs))

    stop_rows = []
    for code, words in lang._STOP.items():
        items = ", ".join(quote(w) for w in sorted(words))
        stop_rows.append('        STOP.put(%s, Set.of(%s));' % (quote(code), items))

    header = '''// GENERATED by laya-java/scripts/gen_language_tables.py -- do not edit.
//
// Regenerate with:
//     python laya-java/scripts/gen_language_tables.py
// and `--check` fails when the committed copy no longer matches laya/lang.py.
package com.convaiinnovations.laya.lang;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * The word lists, script ranges and thresholds {@code laya/lang.py} detects with.
 *
 * <p>Compiled in rather than read from {@code fixtures/lang_tables.json}: a runtime library must
 * not need a test fixture on disk. The fixture keeps its job -- a test asserts this copy equals it,
 * so a table that drifts from Python fails a test rather than changing a routing decision quietly.
 *
 * <p><b>Two orderings are load-bearing.</b> {@link #SCRIPT_RANGES} is scanned in order and the
 * first matching range wins, so a reordering changes which script a code point counts under. And
 * {@link #STOP_WORDS} is iterated to score languages, where the winner is the first of equal
 * scores, so its order decides ties.
 */
public final class LanguageTables {

    private LanguageTables() {
    }

    /** One named non-Latin script and the code-point ranges that belong to it. */
    public record Script(String name, int[] ranges) {
    }

'''
    body = (
        '    /**\n'
        '     * Named scripts, in scan order. The first range that contains a code point wins, so\n'
        '     * this is a sequence and not a set.\n'
        '     */\n'
        '    public static final List<Script> SCRIPT_RANGES = List.of(\n'
        + ",\n".join(script_rows) + ");\n\n"
        '    /**\n'
        '     * Function words per language, in the order Python declares them.\n'
        '     *\n'
        '     * <p>A {@link LinkedHashMap}, because the language that wins a tied score is the\n'
        '     * first one iterated.\n'
        '     */\n'
        '    public static final Map<String, Set<String>> STOP_WORDS;\n\n'
        '    static {\n'
        '        Map<String, Set<String>> STOP = new LinkedHashMap<>();\n'
        + "\n".join(stop_rows) + "\n"
        '        STOP_WORDS = Collections.unmodifiableMap(STOP);\n'
        '    }\n\n'
        + words_block("SHORT_SWEDISH_WORDS", lang._SHORT_SWEDISH_WORDS,
                      "Distinctive Swedish words that name the language from a short input.")
        + "\n"
        + words_block("NON_EN_DIACRITICS", lang._NON_EN_DIACRITICS,
                      "Letters whose presence is evidence the text is not English.")
        + "\n"
        + words_block("SHARED_WORDS", lang._SHARED_WORDS,
                      "Function words several lists hold, which therefore name no language.")
        + "\n"
        + words_block("NORDIC_OVERLAP_WORDS", lang._NORDIC_OVERLAP_WORDS,
                      "Markers shared by Swedish and Danish: evidence of non-English, not of which.")
        + "\n"
        + words_block("EN_ONLY_WORDS", lang._EN_ONLY_WORDS,
                      "English function words no other list holds.")
        + "\n"
        + words_block("EN_COLLISION_WORDS", lang._EN_COLLISION_WORDS,
                      "Words that collide with English, counted once however often they repeat.")
        + '''
    /**
     * A diacritic rate at or above this is evidence the text is not English, even with no stopword
     * match. Measured over every character, so one accented loanword in a short sentence clears it
     * -- which is what the English rescue exists to answer.
     */
    public static final double NON_EN_DIACRITIC_RATE = %r;

    /** Above this rate, English function words no longer rescue the text. */
    public static final double ENGLISH_RESCUE_DIACRITIC_RATE = %r;

    /** Non-Latin share at which non-Latin text is not for the English checkpoint. */
    public static final double NON_LATIN_FRACTION = %r;

    /** The lower share that counts when there are enough letters to dilute it. */
    public static final double NON_LATIN_MIN_FRACTION = %r;

    /** How many non-Latin letters make the lower share count. */
    public static final int NON_LATIN_MIN_LETTERS = %d;
}
''' % (lang.NON_EN_DIACRITIC_RATE, lang.ENGLISH_RESCUE_DIACRITIC_RATE,
       lang.NON_LATIN_FRACTION, lang.NON_LATIN_MIN_FRACTION, lang.NON_LATIN_MIN_LETTERS)
    )
    return header + body


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="do not write; exit 1 if the committed copy would change")
    args = parser.parse_args(argv)
    fresh = render()
    target = os.path.normpath(TARGET)
    if args.check:
        try:
            with open(target, encoding="utf-8") as handle:
                current = handle.read()
        except OSError:
            print("gen_language_tables: %s is missing" % target, file=sys.stderr)
            return 1
        if current != fresh:
            print("gen_language_tables: %s is stale; run "
                  "laya-java/scripts/gen_language_tables.py and commit the result" % target,
                  file=sys.stderr)
            return 1
        print("gen_language_tables: LanguageTables.java matches laya/lang.py")
        return 0
    os.makedirs(os.path.dirname(target), exist_ok=True)
    with open(target, "w", encoding="utf-8") as handle:
        handle.write(fresh)
    print("wrote %s (%d bytes)" % (os.path.relpath(target, REPO), len(fresh)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
