#!/usr/bin/env python3
"""Generate the Unicode tables `laya.lang`'s character predicates need, as Java source.

WHY A GENERATED TABLE RATHER THAN THE JDK'S OWN PREDICATES. `laya/lang.py` leans on three
character properties, and the JDK disagrees with CPython about all three:

  * `str.isalpha()` is categories Lu/Ll/Lt/Lm/Lo, which IS what `Character.isLetter` means -- but
    JDK 17 ships Unicode 13.0 and CPython 3.12 ships 15.0, so the JDK does not know 4,863 of the
    code points Python calls letters (U+0870 Arabic Extended-B, U+11F00 Kawi, ...). It reports them
    UNASSIGNED, so text in a recently-added script would be counted under no script at all and
    routed to the English checkpoint.
  * Python's `\\w` minus `\\d` minus `_` is letters plus the Nl and No numeric categories, which has
    the same version gap.
  * `unicodedata.combining(ch) != 0` is the canonical combining CLASS, which the JDK does not
    expose at all. Approximating it with the Mn and Mc categories -- which is what the .NET port
    does -- is wrong on 1,460 code points: 1,410 it would call combining that Python does not
    (U+034F COMBINING GRAPHEME JOINER among them, class 0) and 50 it would miss.

So the tables are recorded from CPython here and compiled in. That also makes the predicates
independent of the JDK a consumer happens to run, which matters more than it sounds: a JDK upgrade
must not silently change which script a request is detected as.

    python laya-java/scripts/gen_unicode_tables.py            # write
    python laya-java/scripts/gen_unicode_tables.py --check     # fail if the committed copy differs
"""
import argparse
import os
import re
import sys
import unicodedata

HERE = os.path.dirname(os.path.abspath(__file__))
TARGET = os.path.join(
    HERE, "..", "laya-java", "src", "main", "java", "com", "convaiinnovations", "laya", "lang",
    "UnicodeTables.java")

WORD = re.compile(r"[^\W\d_]", re.UNICODE)
DIGIT = re.compile(r"\d", re.UNICODE)
MAX = 0x110000
SURROGATES = range(0xD800, 0xE000)


def ranges(predicate):
    """Inclusive [lo, hi] runs where `predicate` holds. Surrogates never hold."""
    out, start = [], None
    for cp in range(MAX):
        hit = False if cp in SURROGATES else predicate(cp)
        if hit and start is None:
            start = cp
        elif not hit and start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, MAX - 1))
    return out


def table(name, rows, doc):
    """One flat `int[]` of lo, hi pairs, wrapped at a readable width."""
    flat = [str(value) for row in rows for value in row]
    lines, current = [], "            "
    for item in flat:
        piece = item + ", "
        if len(current) + len(piece) > 100:
            lines.append(current.rstrip())
            current = "            "
        current += piece
    if current.strip():
        lines.append(current.rstrip().rstrip(","))
    body = "\n".join(lines)
    return ('    /**\n     * %s\n     *\n     * <p>%d ranges covering %d code points, recorded\n'
            '     * from CPython %s.\n     */\n'
            '    private static final int[] %s = {\n%s\n    };\n'
            % (doc, len(rows), sum(b - a + 1 for a, b in rows),
               unicodedata.unidata_version, name, body))


def render():
    alpha = ranges(lambda cp: chr(cp).isalpha())
    word = ranges(lambda cp: WORD.fullmatch(chr(cp)) is not None)
    combining = ranges(lambda cp: unicodedata.combining(chr(cp)) != 0)
    digit = ranges(lambda cp: DIGIT.fullmatch(chr(cp)) is not None)
    upper = ranges(lambda cp: chr(cp).isupper())
    lower = ranges(lambda cp: chr(cp).islower())

    # Every code point whose lowercase is more than one code point. In Unicode 15 there is
    # exactly one, and `laya/lang.py` depends on it: it replaces U+0130 before lowering, because
    # otherwise the line-length reasoning in `_leaf_non_english` would be wrong.
    multi = []
    for cp in range(MAX):
        if cp in SURROGATES:
            continue
        low = chr(cp).lower()
        if len(low) > 1:
            multi.append((cp, [ord(c) for c in low]))

    header = '''// GENERATED by laya-java/scripts/gen_unicode_tables.py -- do not edit.
//
// Regenerate with:
//     python laya-java/scripts/gen_unicode_tables.py
// and `--check` fails when the committed copy no longer matches CPython.
package com.convaiinnovations.laya.lang;

/**
 * The Unicode properties {@code laya.lang} depends on, recorded from CPython %s.
 *
 * <p>Compiled in rather than read from the JDK, because the JDK disagrees with CPython about all
 * three of them. {@code Character.isLetter} means the same categories as {@code str.isalpha()},
 * but JDK 17 ships Unicode 13.0 against CPython's 15.0 and therefore does not know %d of the code
 * points Python calls letters -- it reports them unassigned, which would count text in a
 * recently-added script under no script at all and route it to the English checkpoint. The
 * canonical combining class is not exposed by the JDK at all, and the Mn/Mc categories are not a
 * substitute: they differ from it on 1,460 code points, including U+034F COMBINING GRAPHEME
 * JOINER, whose class is zero.
 *
 * <p>A table also makes detection independent of the JDK a consumer runs, which matters more than
 * it sounds: a JDK upgrade must not silently change which script a request is detected as.
 */
public final class UnicodeTables {

    /** The CPython release these tables were recorded from. */
    public static final String UNICODE_VERSION = "%s";

    private UnicodeTables() {
    }

''' % (unicodedata.unidata_version, 4863, unicodedata.unidata_version)

    body = (
        table("ALPHA", alpha,
              "Python's {@code str.isalpha()}: categories Lu, Ll, Lt, Lm and Lo.")
        + "\n"
        + table("WORD", word,
                "Python's {@code [^\\\\W\\\\d_]}: letters plus the Nl and No numeric categories, "
                "which is\n     * what {@code laya.lang}'s word regex matches.")
        + "\n"
        + table("COMBINING", combining,
                "Code points with a non-zero canonical combining class.")
        + "\n"
        + table("DIGIT", digit,
                "Python's {@code \\\\d}: the Nd category. Needed because Python's {@code \\\\w} is\n"
                "     * letters plus every numeric category, and the regexes subtract {@code \\\\d} from it.")
        + "\n"
        + table("UPPER", upper, "Python's {@code str.isupper()} for one character.")
        + "\n"
        + table("LOWER", lower, "Python's {@code str.islower()} for one character.")
    )

    multi_cases = "\n".join(
        '            case 0x%04X:\n                return "%s";'
        % (cp, "".join("\\u%04X" % c for c in low)) for cp, low in multi)
    methods = '''
    /** Python's {@code str.isalpha()} for one code point. */
    public static boolean isAlpha(int codePoint) {
        return contains(ALPHA, codePoint);
    }

    /** Python's {@code [^\\\\W\\\\d_]} for one code point: a word character that is not a digit. */
    public static boolean isWordChar(int codePoint) {
        return contains(WORD, codePoint);
    }

    /** Whether {@code unicodedata.combining} would return non-zero for this code point. */
    public static boolean isCombining(int codePoint) {
        return contains(COMBINING, codePoint);
    }

    /** Python's {@code \\d}: the Nd category. The JDK misses 30 of these at Unicode 13. */
    public static boolean isDigit(int codePoint) {
        return contains(DIGIT, codePoint);
    }

    /**
     * Python's {@code \\w} for a str: alphanumeric or underscore.
     *
     * <p>Spelled out because the regexes in {@code laya/lang.py} subtract from it --
     * {@code [^\\W\\d_]} is this minus digits and underscore, {@code [^\\W_]} is this minus
     * underscore -- and Java's own {@code \\w} is a different set again (it admits combining
     * marks and join controls, which Python's does not).
     */
    public static boolean isPythonWordChar(int codePoint) {
        return codePoint == '_' || isWordChar(codePoint) || isDigit(codePoint);
    }

    /** Python's {@code [^\\W_]}: a word character that is not the underscore. */
    public static boolean isWordOrDigit(int codePoint) {
        return isWordChar(codePoint) || isDigit(codePoint);
    }

    /**
     * Python's {@code str.isupper()} for one code point.
     *
     * <p>A table, because {@code Character.isUpperCase} misses 40 of these and
     * {@code Character.isLowerCase} misses 200 at Unicode 13 -- U+10FC, a Georgian modifier
     * letter Python calls lowercase through Other_Lowercase, among them. Detection reads the case
     * of the first letter of a non-Latin run to tell a proper noun from a request, so a letter
     * whose case the JDK does not know would change that decision.
     */
    public static boolean isUpper(int codePoint) {
        return contains(UPPER, codePoint);
    }

    /** Python's {@code str.islower()} for one code point. */
    public static boolean isLower(int codePoint) {
        return contains(LOWER, codePoint);
    }

    /** Whether a code point has case at all, which is what {@code str.isupper()} requires one of. */
    public static boolean isCased(int codePoint) {
        return isUpper(codePoint) || isLower(codePoint)
                || Character.getType(codePoint) == Character.TITLECASE_LETTER;
    }

    /**
     * Python's {@code str.isupper()} for a whole string: at least one cased code point, and every
     * cased code point uppercase.
     */
    public static boolean isUpperString(String text) {
        boolean sawCased = false;
        int i = 0;
        while (i < text.length()) {
            int codePoint = text.codePointAt(i);
            i += Character.charCount(codePoint);
            if (!isCased(codePoint)) {
                continue;
            }
            if (!isUpper(codePoint)) {
                return false;
            }
            sawCased = true;
        }
        return sawCased;
    }

    /** Whether any code point of {@code text} is lowercase, as Python's {@code islower} sees it. */
    public static boolean hasLower(String text) {
        int i = 0;
        while (i < text.length()) {
            int codePoint = text.codePointAt(i);
            i += Character.charCount(codePoint);
            if (isLower(codePoint)) {
                return true;
            }
        }
        return false;
    }

    /**
     * Python's {@code str.lower()}, which is not Java's.
     *
     * <p>{@link String#toLowerCase} applies the contextual rules, so {@code "\\u0391\\u03A3"}
     * lowercases to {@code "\\u03B1\\u03C2"} -- a FINAL sigma -- where Python gives
     * {@code "\\u03B1\\u03C3"}. Lowercasing one code point at a time removes the context and
     * therefore the rule. Verified over every code point in Unicode: with the multi-character
     * mapping below handled explicitly, the two agree exactly.
     */
    public static String pythonLower(String text) {
        StringBuilder out = new StringBuilder(text.length());
        int i = 0;
        while (i < text.length()) {
            int codePoint = text.codePointAt(i);
            i += Character.charCount(codePoint);
            String expanded = multiCharLower(codePoint);
            if (expanded != null) {
                out.append(expanded);
            } else {
                out.appendCodePoint(Character.toLowerCase(codePoint));
            }
        }
        return out.toString();
    }

    /**
     * The one code point whose Python lowercase is longer than one code point.
     *
     * <p>{@code laya.lang} depends on it: it replaces U+0130 before lowering, because the
     * line-length reasoning in its leaf scan counts code points on the RAW line and this mapping
     * would otherwise make a four-character line reach four word tokens.
     */
    private static String multiCharLower(int codePoint) {
        switch (codePoint) {
%s
            default:
                return null;
        }
    }

    /** Binary search over a flat array of inclusive [lo, hi] pairs. */
    private static boolean contains(int[] pairs, int codePoint) {
        int low = 0;
        int high = pairs.length / 2 - 1;
        while (low <= high) {
            int mid = (low + high) >>> 1;
            if (codePoint < pairs[mid * 2]) {
                high = mid - 1;
            } else if (codePoint > pairs[mid * 2 + 1]) {
                low = mid + 1;
            } else {
                return true;
            }
        }
        return false;
    }
}
''' % multi_cases
    return header + body + methods


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="do not write; exit 1 if the committed copy would change")
    args = parser.parse_args(argv)
    fresh = render()
    target = os.path.normpath(TARGET)
    if args.check:
        try:
            with open(target, encoding="utf-8") as handle:
                current = handle.read()
        except OSError:
            print("gen_unicode_tables: %s is missing" % target, file=sys.stderr)
            return 1
        if current != fresh:
            print("gen_unicode_tables: %s is stale; run "
                  "laya-java/scripts/gen_unicode_tables.py and commit the result" % target,
                  file=sys.stderr)
            return 1
        print("gen_unicode_tables: UnicodeTables.java matches CPython %s"
              % unicodedata.unidata_version)
        return 0
    os.makedirs(os.path.dirname(target), exist_ok=True)
    with open(target, "w", encoding="utf-8") as handle:
        handle.write(fresh)
    print("wrote %s (%d bytes)" % (os.path.relpath(target, os.path.join(HERE, "..", "..")),
                                   len(fresh)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
