"""Generate TypeScript presets from Python without importing the ML runtime."""
import argparse
import importlib.util
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
spec = importlib.util.spec_from_file_location("laya_presets", ROOT / "laya/presets.py")
presets = importlib.util.module_from_spec(spec)
spec.loader.exec_module(presets)

output = [
    "// Generated by scripts/sync_presets.py. Edit laya/presets.py, then regenerate.\n",
    "import type { JsonValue, Questions } from './types.js';\n\n",
]
for name in ["triage", "email", "guard", "moderation", "router"]:
    value = getattr(presets, name + "_questions")()
    output.append(f"const {name}Preset = {json.dumps(value, ensure_ascii=False, indent=2)} as const satisfies Questions;\n\n")
    if name != "email":
        output.append(f"export function {name}Questions(): typeof {name}Preset {{\n"
                      f"  return structuredClone({name}Preset);\n}}\n\n")

output.append('''export function emailQuestions(): typeof emailPreset;
export function emailQuestions<const C extends Readonly<Record<string, JsonValue>>>(categories: C):
  Omit<typeof emailPreset, 'category'> & { category: Omit<typeof emailPreset.category, 'criteria'> & { criteria: C } };
export function emailQuestions(categories?: Readonly<Record<string, JsonValue>>) {
  const preset = structuredClone(emailPreset);
  return { ...preset, category: { ...preset.category, criteria: categories === undefined
    ? preset.category.criteria : structuredClone(categories) } };
}
''')

target = ROOT / "sdk/typescript/src/presets.ts"
content = "".join(output)
parser = argparse.ArgumentParser()
parser.add_argument("--check", action="store_true")
args = parser.parse_args()
if args.check:
    if not target.exists() or target.read_text(encoding="utf-8") != content:
        raise SystemExit("Presets are stale. Run python sdk/typescript/scripts/sync_presets.py")
else:
    target.write_text(content, encoding="utf-8")
