// GENERATED by laya-java/scripts/gen_language_tables.py -- do not edit.
//
// Regenerate with:
//     python laya-java/scripts/gen_language_tables.py
// and `--check` fails when the committed copy no longer matches laya/lang.py.
package com.convaiinnovations.laya.lang;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * The word lists, script ranges and thresholds {@code laya/lang.py} detects with.
 *
 * <p>Compiled in rather than read from {@code fixtures/lang_tables.json}: a runtime library must
 * not need a test fixture on disk. The fixture keeps its job -- a test asserts this copy equals it,
 * so a table that drifts from Python fails a test rather than changing a routing decision quietly.
 *
 * <p><b>Two orderings are load-bearing.</b> {@link #SCRIPT_RANGES} is scanned in order and the
 * first matching range wins, so a reordering changes which script a code point counts under. And
 * {@link #STOP_WORDS} is iterated to score languages, where the winner is the first of equal
 * scores, so its order decides ties.
 */
public final class LanguageTables {

    private LanguageTables() {
    }

    /** One named non-Latin script and the code-point ranges that belong to it. */
    public record Script(String name, int[] ranges) {
    }

    /**
     * Named scripts, in scan order. The first range that contains a code point wins, so
     * this is a sequence and not a set.
     */
    public static final List<Script> SCRIPT_RANGES = List.of(
            new Script("greek", new int[] {880, 1023, 7936, 8191}),
            new Script("cyrillic", new int[] {1024, 1327, 11744, 11775, 42560, 42655}),
            new Script("armenian", new int[] {1328, 1423}),
            new Script("hebrew", new int[] {1424, 1535}),
            new Script("arabic", new int[] {1536, 1791, 1872, 1919, 2208, 2303, 64336, 65023, 65136, 65279}),
            new Script("devanagari", new int[] {2304, 2431, 43232, 43263}),
            new Script("bengali", new int[] {2432, 2559}),
            new Script("gurmukhi", new int[] {2560, 2687}),
            new Script("gujarati", new int[] {2688, 2815}),
            new Script("oriya", new int[] {2816, 2943}),
            new Script("tamil", new int[] {2944, 3071}),
            new Script("telugu", new int[] {3072, 3199}),
            new Script("kannada", new int[] {3200, 3327}),
            new Script("malayalam", new int[] {3328, 3455}),
            new Script("sinhala", new int[] {3456, 3583}),
            new Script("thai", new int[] {3584, 3711}),
            new Script("lao", new int[] {3712, 3839}),
            new Script("tibetan", new int[] {3840, 4095}),
            new Script("myanmar", new int[] {4096, 4255}),
            new Script("georgian", new int[] {4256, 4351}),
            new Script("ethiopic", new int[] {4608, 4991}),
            new Script("khmer", new int[] {6016, 6143}),
            new Script("hangul", new int[] {4352, 4607, 12592, 12687, 44032, 55215}),
            new Script("kana", new int[] {12352, 12447, 12448, 12543, 12784, 12799}),
            new Script("han", new int[] {13312, 19903, 19968, 40959, 63744, 64255}));

    /**
     * Function words per language, in the order Python declares them.
     *
     * <p>A {@link LinkedHashMap}, because the language that wins a tied score is the
     * first one iterated.
     */
    public static final Map<String, Set<String>> STOP_WORDS;

    static {
        Map<String, Set<String>> STOP = new LinkedHashMap<>();
        STOP.put("en", Set.of("and", "are", "as", "at", "be", "but", "can", "for", "from", "has", "have", "i", "in", "is", "it", "not", "of", "on", "please", "that", "the", "their", "there", "this", "to", "was", "we", "were", "what", "which", "will", "with", "would", "you"));
        STOP.put("fr", Set.of("alors", "au", "aux", "avec", "bien", "bonjour", "ce", "ces", "cette", "comment", "dans", "des", "deux", "dois", "doit", "donc", "du", "elle", "elles", "est", "et", "fait", "fois", "il", "ils", "je", "jour", "jours", "la", "le", "les", "ma", "mais", "merci", "mes", "mois", "mon", "nous", "ont", "ou", "pas", "peut", "peux", "plus", "pour", "pourquoi", "quand", "que", "qui", "sa", "ses", "sont", "sur", "ta", "tes", "ton", "tous", "tout", "toute", "trois", "tr\u00E8s", "tu", "une", "veut", "veux", "vous", "\u00EAtre"));
        STOP.put("de", Set.of("aber", "auch", "auf", "aus", "bei", "bitte", "das", "dem", "den", "der", "dich", "die", "diese", "diesen", "dieser", "dieses", "dir", "ein", "eine", "einem", "einen", "einer", "f\u00FCr", "gibt", "habe", "haben", "heute", "ich", "im", "in", "ist", "jetzt", "kann", "kannst", "mein", "meine", "meinem", "meinen", "meiner", "mich", "mir", "mit", "nach", "nicht", "noch", "oder", "sich", "sind", "und", "uns", "von", "wann", "was", "welche", "werden", "wie", "wir", "wird", "wo", "wurde", "zu", "zum", "zur"));
        STOP.put("es", Set.of("al", "algo", "aqu\u00ED", "aunque", "como", "con", "cuando", "del", "donde", "dos", "el", "entre", "es", "esa", "ese", "eso", "esta", "este", "esto", "est\u00E1", "fue", "fueron", "gracias", "han", "hay", "hemos", "hoy", "la", "las", "le", "les", "lo", "los", "mi", "muy", "m\u00E1s", "nada", "necesito", "ni", "nos", "para", "pero", "por", "porque", "puede", "pueden", "que", "quiero", "se", "ser", "sobre", "son", "su", "sus", "tambi\u00E9n", "tengo", "tiene", "tienen", "todo", "tres", "tu", "un", "una", "y", "ya"));
        STOP.put("pt", Set.of("agora", "ainda", "alguem", "algu\u00E9m", "ali", "antes", "ao", "aos", "aqui", "as", "at\u00E9", "boa", "cad\u00EA", "com", "como", "consigo", "da", "das", "depois", "deu", "do", "dois", "dos", "e", "em", "entao", "ent\u00E3o", "era", "esta", "estamos", "estava", "este", "estou", "est\u00E1", "eu", "ficou", "fiz", "foi", "gostaria", "hoje", "isso", "isto", "ja", "j\u00E1", "mais", "mas", "meu", "meus", "minha", "minhas", "muito", "na", "nada", "nao", "nas", "nenhum", "nenhuma", "ninguem", "ningu\u00E9m", "noite", "nos", "nossa", "nosso", "n\u00E3o", "o", "obrigada", "obrigado", "ol\u00E1", "onde", "ontem", "os", "para", "pela", "pelo", "pode", "podem", "por", "porque", "pra", "preciso", "quando", "que", "quero", "sao", "se", "ser", "seu", "sou", "sua", "s\u00E3o", "tambem", "tamb\u00E9m", "tarde", "tem", "tenho", "tr\u00EAs", "tudo", "t\u00E1", "um", "uma", "vc", "vcs", "voce", "voces", "voc\u00EA", "voc\u00EAs", "\u00E9"));
        STOP.put("it", Set.of("abbiamo", "adesso", "agli", "alla", "alle", "anche", "ancora", "avete", "che", "ci", "ciao", "col", "come", "con", "da", "dagli", "dal", "dalla", "dallo", "degli", "dei", "del", "della", "delle", "dello", "deve", "devo", "devono", "di", "dove", "e", "ed", "era", "fra", "gi\u00E0", "gli", "grazie", "ha", "hai", "hanno", "ho", "ieri", "il", "la", "le", "lo", "mai", "mi", "mia", "mio", "molto", "ne", "negli", "nel", "nell", "nella", "non", "o", "oggi", "per", "perche", "pi\u00F9", "poco", "quando", "questa", "questo", "scusa", "sempre", "si", "sono", "stata", "stato", "su", "sua", "sul", "sulla", "sulle", "tra", "tuo", "un", "una", "uno", "voglio", "vorrei", "\u00E8"));
        STOP.put("nl", Set.of("aan", "dat", "deze", "door", "een", "het", "is", "maar", "met", "naar", "niet", "ook", "op", "te", "van", "voor", "worden", "wordt", "zijn"));
        STOP.put("sv", Set.of("appen", "aterbetala", "aterbetalning", "att", "behover", "beh\u00F6ver", "blivit", "debiterade", "dessa", "detta", "faktura", "fel", "fr\u00E5n", "f\u00E5r", "ganger", "g\u00E5ng", "g\u00E5nger", "g\u00F6r", "g\u00F6ra", "hittar", "hjalp", "hjalpa", "hj\u00E4lp", "hj\u00E4lpa", "h\u00E4r", "installningarna", "installningen", "inst\u00E4llningarna", "inst\u00E4llningen", "inte", "jag", "kommer", "kraschar", "kvittot", "losenord", "l\u00F6senord", "mig", "min", "mitt", "m\u00E5ste", "nar", "n\u00E4r", "n\u00E4sta", "och", "ocks\u00E5", "om", "oppnar", "paket", "ska", "skicka", "skulle", "sparningen", "sp\u00E5rningen", "s\u00E4ger", "till", "tva", "tv\u00E5", "upp", "uppdaterats", "utan", "vi", "vill", "\u00E4r", "\u00E5terbetala", "\u00E5terbetalning", "\u00F6ppnar"));
        STOP.put("ro", Set.of("aceasta", "aceast\u0103", "acest", "acesta", "acum", "ale", "care", "dar", "din", "dup\u0103", "este", "foarte", "fost", "f\u0103r\u0103", "lui", "mi", "nu", "pentru", "p\u00E2n\u0103", "sunt", "s\u0103", "trebuie", "vreau", "v\u0103", "\u00EEn", "\u0219i", "\u021Bi"));
        STOP.put("bn", Set.of("abar", "ajke", "akhon", "amader", "amake", "amar", "ami", "amra", "apnake", "apnar", "apnara", "apni", "ar", "asbe", "bhai", "bhalo", "bolte", "bolun", "chai", "chaina", "dhonnobad", "dilam", "dite", "diye", "diyechi", "dorkar", "duibar", "ei", "eita", "ekbar", "ekhon", "ekhono", "ekta", "ferot", "geche", "gese", "hobe", "hocche", "hoise", "hoye", "hoyeche", "hoyni", "jabe", "jodi", "jonno", "kalke", "keno", "keu", "kharap", "khub", "ki", "kibhabe", "kichu", "kintu", "kivabe", "kobe", "kokhon", "korbo", "korchi", "kore", "koreche", "korechi", "koren", "korlam", "korsi", "korte", "korun", "kothay", "koto", "lagbe", "moddhe", "nai", "niye", "oi", "oita", "onek", "ota", "pabo", "paini", "parben", "parbo", "parchi", "parchina", "peyechi", "sathe", "shathe", "shob", "shomossa", "somossa", "tader", "tahole", "taka", "theke", "tomake", "tomar", "tomra", "tumi", "valo"));
        STOP.put("az", Set.of("amma", "ancaq", "artiq", "art\u0131q", "bir", "biz", "bu", "cox", "daha", "deyil", "d\u0259", "eger", "g\u00F6r\u0259", "h\u0259m", "h\u0259r", "ile", "il\u0259", "is\u0259", "kimi", "lakin", "m\u0259n", "n\u0259", "olan", "olmasa", "olub", "onlar", "siz", "sonra", "s\u0259n", "ucun", "var", "ve", "v\u0259", "yalniz", "yaln\u0131z", "yox", "yoxdur", "\u00E7ox", "\u00FC\u00E7\u00FCn", "\u0259g\u0259r"));
        STOP_WORDS = Collections.unmodifiableMap(STOP);
    }

    /** Distinctive Swedish words that name the language from a short input. */
    public static final Set<String> SHORT_SWEDISH_WORDS = Set.of(
            "abonnemanget", "aterbetalning", "atkomst", "behover", "beh\u00F6ver", "betalningen",
            "fakturan", "felmeddelande", "glomt", "gl\u00F6mt", "inloggningen", "installningen",
            "inst\u00E4llningen", "kvitto", "kvittot", "losenord", "l\u00F6senord", "sparningen",
            "sp\u00E5rningen", "\u00E5terbetalning", "\u00E5tkomst");

    /** Letters whose presence is evidence the text is not English. */
    public static final Set<String> NON_EN_DIACRITICS = Set.of(
            "\u00DF", "\u00E0", "\u00E1", "\u00E2", "\u00E3", "\u00E4", "\u00E5", "\u00E6", "\u00E7",
            "\u00E8", "\u00E9", "\u00EA", "\u00EB", "\u00EC", "\u00ED", "\u00EE", "\u00EF", "\u00F1",
            "\u00F2", "\u00F3", "\u00F4", "\u00F5", "\u00F6", "\u00F8", "\u00F9", "\u00FA", "\u00FB",
            "\u00FC", "\u00FD", "\u00FF", "\u0101", "\u0103", "\u0105", "\u0107", "\u010D", "\u010F",
            "\u0111", "\u0113", "\u0119", "\u011B", "\u011F", "\u0123", "\u012B", "\u0131", "\u0137",
            "\u013C", "\u0142", "\u0144", "\u0146", "\u0148", "\u0151", "\u0153", "\u0159", "\u015B",
            "\u015F", "\u0161", "\u0163", "\u0165", "\u016B", "\u016F", "\u0171", "\u017A", "\u017C",
            "\u017E", "\u0219", "\u021B", "\u0259");

    /** Function words several lists hold, which therefore name no language. */
    public static final Set<String> SHARED_WORDS = Set.of(
            "as", "como", "con", "da", "das", "del", "dois", "dos", "e", "era", "esta", "este",
            "est\u00E1", "f\u00E5r", "hej", "il", "in", "is", "ja", "jo", "kommer", "la", "le", "les",
            "lo", "mais", "mi", "mig", "min", "nada", "nej", "nos", "o", "om", "para", "por", "porque",
            "quando", "que", "se", "ser", "skulle", "su", "sua", "tack", "tu", "un", "una", "vi",
            "was");

    /** Markers shared by Swedish and Danish: evidence of non-English, not of which. */
    public static final Set<String> NORDIC_OVERLAP_WORDS = Set.of(
            "f\u00E5r", "hej", "ja", "jo", "kommer", "mig", "min", "nej", "om", "skulle", "tack", "vi");

    /** English function words no other list holds. */
    public static final Set<String> EN_ONLY_WORDS = Set.of(
            "and", "are", "at", "be", "but", "can", "for", "from", "has", "have", "i", "it", "not",
            "of", "on", "please", "that", "the", "their", "there", "this", "to", "we", "were", "what",
            "which", "will", "with", "would", "you");

    /** Words that collide with English, counted once however often they repeat. */
    public static final Set<String> EN_COLLISION_WORDS = Set.of(
            "care", "come", "do", "im", "per", "plus", "son", "todo");

    /**
     * A diacritic rate at or above this is evidence the text is not English, even with no stopword
     * match. Measured over every character, so one accented loanword in a short sentence clears it
     * -- which is what the English rescue exists to answer.
     */
    public static final double NON_EN_DIACRITIC_RATE = 0.02;

    /** Above this rate, English function words no longer rescue the text. */
    public static final double ENGLISH_RESCUE_DIACRITIC_RATE = 0.06;

    /** Non-Latin share at which non-Latin text is not for the English checkpoint. */
    public static final double NON_LATIN_FRACTION = 0.2;

    /** The lower share that counts when there are enough letters to dilute it. */
    public static final double NON_LATIN_MIN_FRACTION = 0.1;

    /** How many non-Latin letters make the lower share count. */
    public static final int NON_LATIN_MIN_LETTERS = 10;
}
