using System.Text.Json;

namespace Laya.Tests;

/// <summary>
/// Tier 1: the hashing embedder against every entry of
/// <c>golden/routing/hashing_embedder_probe.json</c>, which was generated by
/// <c>laya-dotnet/tools/hashing_embedder.py</c>. Every language's port must agree bit-for-bit, because the
/// shortlist goldens and every SDK's sample were recorded with it.
/// </summary>
public sealed class HashingEmbedderTests
{
    public static IEnumerable<object[]> ProbeCases()
    {
        using var doc = RoutingGoldenData.Load("hashing_embedder_probe.json");
        // Index by position, not by text: several probe entries share the same text after
        // trimming display, and whitespace-only text has no useful theory-case label anyway.
        return
        [
            .. Enumerable.Range(0, doc.RootElement.GetArrayLength()).Select(i => new object[] { i }),
        ];
    }

    [Theory]
    [MemberData(nameof(ProbeCases))]
    public void EveryProbeEntry(int index)
    {
        using var doc = RoutingGoldenData.Load("hashing_embedder_probe.json");
        var entry = doc.RootElement[index];
        var text = entry.GetProperty("text").GetString()!;
        var expected = entry.GetProperty("vector").EnumerateArray().Select(e => e.GetDouble()).ToArray();

        var actual = HashingEmbedder.EmbedOne(text);

        Assert.Equal(HashingEmbedder.Dimension, actual.Length);
        Assert.Equal(expected.Length, actual.Length);
        for (var i = 0; i < expected.Length; i++)
            Assert.True(expected[i] == actual[i],
                $"text {JsonSerializer.Serialize(text)} bucket {i}: python {expected[i]}, dotnet {actual[i]}");
    }

    [Fact]
    public void EmbedBatchesInOrderAndMatchesEmbedOne()
    {
        var texts = new[] { "alpha", "beta", "gamma" };
        var batch = HashingEmbedder.Embed(texts);
        Assert.Equal(texts.Length, batch.Length);
        for (var i = 0; i < texts.Length; i++)
            Assert.Equal(HashingEmbedder.EmbedOne(texts[i]), batch[i]);
    }

    [Fact]
    public void EmptyBatchReturnsEmptyResult() => Assert.Empty(HashingEmbedder.Embed([]));

    [Fact]
    public void TurkishCapitalIWithDotUsesTheTwoCodePointLowercasing()
    {
        // Regression guard for the InvariantGlobalization pitfall documented on HashingEmbedder:
        // plain ToLowerInvariant() would leave U+0130 untouched instead of expanding it.
        var istanbul = HashingEmbedder.EmbedOne("İstanbul");
        var alreadyLower = HashingEmbedder.EmbedOne("i̇stanbul"); // "i" + combining dot above
        Assert.Equal(alreadyLower, istanbul);
    }
}
